apiVersion: v1
kind: Namespace
metadata:
  name: smartdns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartdns-deployment
  namespace: smartdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartdns
  template:
    metadata:
      labels:
        app: smartdns
      containers:
        - name: smartdns
          image: samuel19982/dns:latest
          env:
            - name: PARAMS
              value: 'run -c /etc/smartdns/smartdns.conf -d'
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 10
            tcpSocket:
              port: 53
          ports:
            - containerPort: 53 #dns
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: smartdns-service
  namespace: smartdns
spec:
  selector:
    app: smartdns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
  type: LoadBalancer