version: '3.4'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    env_file:
      - vaultwarden.env
    environment:
      - SIGNUPS_ALLOWED=${SIGNUP_ALLOWED} # prevent that anybody else can login
      - DISABLE_ADMIN_TOKEN=${DISABLE_ADMIN_TOKEN} # turn off admin access for security
    volumes:
      - ${VOLUME_MOUNT}:/data # Mapped persistent storage
    ports:
      - ${PORT}:80
    restart: always